Real_state/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from property import views

#global routers
urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('property/', include(('property.urls', 'property'), namespace='property')),
]

#admin property_management
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



admin.site.site_header = "ANGESCO"
admin.site.site_title = "Gestión Inmobiliaria Portal"
admin.site.index_title = "Bienvenido al portal de Gestión Inmobiliaria ANGESCO"

property/urls.py
from django.urls import path

#All views of the Property application are imported
from  . import views

urlpatterns = [
    path('list/', views.PropertyList.as_view(), name='list'),
    path('detail/<int:pk>/', views.PropertyDetail.as_view(), name='detail'),
    path('search/', views.searchProperty, name='search'),
    path('login/', views.index, name='login'),
    path('create/', views.PropertyCreate.as_view(), name='create'),
    #api services web
    path('api/', views.PropertyAPI.as_view(), name='api'),
    path('api/<int:pk>', views.PropertyAPI.as_view(), name='api'),

    #path('hello/', hello.as_view(), name='hello'),

]

users/urls.py
from django.urls import path

#All views of the Property application are imported
from .views import signup, ActivateUser, templateEmailSent

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>/', ActivateUser, name='activate'),
    path('emailsent/<str:username>/', templateEmailSent, name='emailsent'),
]

templates/base/base.html
{% load static %}
<html>
<head>
  <title>ANGESCO</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/hovereffect.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome-4.7.0/css/font-awesome.min.css' %}">
</head>
<body>
<div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark container">
    <a class="navbar-brand" href="{% url 'index' %}">Inmobiliaria</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
 <!-- Menu principal Options-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item}">
          <a class="nav-link" href="{% url 'property:list' %}">
            Inmuebles <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'property:create' %}">
            Crear Inmuebles <i></i> <span class="sr-only"></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'property:list' %}">

            Propiedades en gestión <span class="sr-only"></span></a>
        </li>

      </ul>
      <form class="form-inline my-2 my-lg-0" action="{% url 'property:search' %}" method="post">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Buscar inmuebles..." name="search" required>
        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Buscar</button>
      </form>
  <!-- Registre Rol-->
      {% if user.is_authenticated %}
        <h6 class="ml-5" style="color:white">Hola {{ user.username }}!</h6>
        <a href="{% url 'logout' %}" class="btn btn-info ml-2">Cerrar Sesión</a>
      {% else %}
        <a href="{% url 'users:signup' %}" class="btn btn-info ml-5">Registrarse</a>
        <a href="{% url 'login' %}" class="btn btn-danger ml-2">Iniciar Sesión</a>
      {% endif %}
    </div>
  </nav>
</div>

{% if request.path == '/' %}

{% endif %}
<!-- here is the content of the subpages-->
{% block content %}
{% endblock %}

{% include "base/footer.html" %}

</body>
<script href="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/base/footer.html
<!-- Footer -->
<footer class="page-footer font-small bg-dark pt-2 mt-3 " style="color:white" >
  <footer class="page-footer font-small blue pt-4">

  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <div class="col-md-5 mt-md-1 mt-8">
        <h5 class="text-uppercase">ANGESCO Inmuebles</h5>
        <ul class="list-unstyled">
          <li class="nav-item">
            <br><a  href="{% url 'property:list' %}" style="color:#888888">
            Quienes Somos <i></i> <span class="sr-only"></span></a>
            <li>
            <br> <img src="../../Image/{{logo.urlimage }}" width="70 %">
            </li>
          </li>
        </ul>
      </div>
      <hr class="clearfix w-200 d-md-none pb-3">
      <div class="col-md-4 mb-md-0 mb-3">
        <h5 class="text-uppercase">Tipo de Inmuebles</h5>
        <ul class="list-unstyled">
          <li>
            <a href="#!" style="color:#888888">Casas</a>
          </li>
          <li>
            <a href="#!" style="color:#888888">Apartamentos</a>
          </li>
          <li>
            <a href="#!" style="color:#888888">Finca</a>
          </li><li>
            <a href="#!" style="color:#888888">Local</a>
          </li>
          <li>
            <a href="#!" style="color:#888888">Venta</a>
          </li>
        </ul>
      </div>
      <div class="col-md-3 mb-md-0 mb-3">
        <h5 class="text-uppercase">Contacto</h5>
        <ul class="list-unstyled">
          <li>
            <a style="color:#888888">Manizales</a>
          </li>
          <li>
            <a style="color:#888888">(3) 89631341</a>
          </li>
          <li>
            <a style="color:#888888">(57) 3137386604</a>
          </li>
          <li>
            <a style="color:#888888">Cra. 23 No 62-39 piso 11</a>
          </li>
          <li>
            <a style="color:#888888">Av. Santander</a>
          </li>
          <li>
            <a style="color:#888888"> Centro Empresarial Capitalia</a>
            </li>
        </ul>
      </div>
    </div>
  </div>
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright |
    <a style="color: #888888">All Rights Reserved | ANGESCO |</a>
    <a style="color: #888888">angesco2020@gmail.com</a>
  </div>
</footer>

templates/base/hello.html
{% extends 'base/base.html' %}

{% load static %}
<!-- Informatión inmobiliaria -->
{% block content %}
<div class="container">
    <h1>Bienvenidos a ANGESCO Inmuebles</h1>
    <div class="row">
      <div class="col-md">
          <div class="card">
              <img src="{% static 'Image/somos.png' %}" class="img-fluid" title="Banner Bienvenida" />
            <div class="card-body">
              <h4 class="card-title">SOMOS</h4>
              <p class="card-text"> ANGESCO es una empresa inmobiliaria activa, dinámica y muy eficiente en la gestión de Inmubles tanto de segunda mano como de nueva promoción. </p>
              <p class="card-text"> Nuestro objetivo es siempre conseguir el mayor bienestar posible en la adquisición de los inmuebles y la mayor eficacia y rentabilidad en el presente
                y el futuro nos adaptándonos a las necesidades del usuario y el cliente brindando un mejor servicio y con un trato personalizado a aquellos propietarios que quieren vender
                 ó alquilar su propiedad y aquellos clientes que buscan una vivienda en compra o alquiler .</p>

              <hr>

                return render(request, hello.html, context)
              </div>
          </div>
      </div>



{% endblock  %}