Real_state/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from property import views

#global routers
urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('property/', include(('property.urls', 'property'), namespace='property')),
]

#admin property_management
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



admin.site.site_header = "ANGESCO"
admin.site.site_title = "Gestión Inmobiliaria Portal"
admin.site.index_title = "Bienvenido al portal de Gestión Inmobiliaria ANGESCO"

property/urls.py
from django.urls import path

#All views of the Property application are imported
from  . import views

urlpatterns = [
    path('list/', views.PropertyList.as_view(), name='list'),
    path('detail/<int:pk>/', views.PropertyDetail.as_view(), name='detail'),
    path('search/', views.searchProperty, name='search'),
    path('login/', views.index, name='login'),
    path('create/', views.PropertyCreate.as_view(), name='create'),
    #api services web
    path('api/', views.PropertyAPI.as_view(), name='api'),
    path('api/<int:pk>', views.PropertyAPI.as_view(), name='api'),

    #path('hello/', hello.as_view(), name='hello'),

]

users/urls.py
from django.urls import path

#All views of the Property application are imported
from .views import signup, ActivateUser, templateEmailSent

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>/', ActivateUser, name='activate'),
    path('emailsent/<str:username>/', templateEmailSent, name='emailsent'),
]

property/models.py
#encoding:utf-8 <- Esta línea permite usar tíldes y caracteres especiales
from django.db import models #Clase con la descripción de modelos
from django.contrib.auth.models import User
import datetime

#Create model Type property
#Properties_type (1= apartment, 2=house 3=local 4=farm)
class Property_type(models.Model):
    name = models.CharField(max_length=30)

# Create model Property State
class Property_state(models.Model):
    name = models.CharField(max_length=50)

# Create model Property Model
class Property(models.Model):
    #string data(cadena), max_length 50
    name = models.CharField(max_length=50, null=False)
    price = models.DecimalField(max_digits=8, decimal_places=0, null= False)
    city = models.CharField(max_length=30)
    neighborhood = models.CharField(max_length=50)
    address = models.CharField(max_length=120)
    length = models.DecimalField(max_digits=4, decimal_places=1)
    antiquity = models.IntegerField()
    floors = models.IntegerField()
    amount_rooms = models.IntegerField()
    bathrooms=models.IntegerField()
    stract = models.IntegerField()
    urlimage = models.ImageField(null=True,upload_to='property/%Y/%m/%d')
    description = models.CharField(max_length=600)
    property_type = models.ForeignKey(Property_type, null=False, on_delete=models.PROTECT)
    property_state = models.ForeignKey(Property_state, null=False, on_delete=models.PROTECT)
    available = models.BooleanField(default=True)


# Create model Property type Management
class Type_management(models.Model):
    name = models.CharField(max_length=50)

# Create model Property Management
class Property_management(models.Model):
    start_date = models.DateTimeField(null=False)
    end_date =  models.DateTimeField(null=False)
    #current_state (1= 1 to 5  years old 2= 5 to 10 yeras old  3= 10 to 20 years old)
    current_state = models.BooleanField(null= False)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    contract_number = models.IntegerField()
    observations = models.CharField(max_length=600)
    user = models.ForeignKey(User, null=False, on_delete=models.PROTECT)
    property = models.ForeignKey(Property, null=False, on_delete=models.PROTECT)
    type_management = models.ForeignKey(Type_management, null=False, on_delete=models.PROTECT)

property/views.py
from django.shortcuts import render
from .models import Property
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView
#imports services web
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import PropertySerializer
#AJAX
from django.urls import reverse_lazy, reverse


def index(request):
    return render(request, 'home.html')

# Properties List
class PropertyList(ListView):
    model = Property

    def get_queryset(self):
        queryset = Property.objects.filter(available=True)
        return queryset

#Property Detail
class PropertyDetail(DetailView):
    model = Property

def searchProperty(request):
    if request.method == 'POST':
        pattern = request.POST['search']
        property = Property.objects.filter(available=True, neighborhood__contains=pattern)
    else:
        property = Property.objects.filter(available=True)
    return render(request, 'property/property_search.html', {'object_list':property, 'search':pattern})


#Web Service Rest
class PropertyAPI(APIView):
    #show all properties
    def get(self, request):
        property = Property.objects.all()
        serializer = PropertySerializer(property, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = PropertySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, pk, format=None):
        property = PropertySerializer.objects.get(pk=pk)
        serializer = PropertySerializer(property, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors)

    def delete(self, request, pk, format=None):
        property = Property.objects.get(pk=pk)
        property.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


#Create property
class PropertyCreate(CreateView):
    model = Property
    success_url = reverse_lazy('property:create')
    fields = '__all__'


    #Property_management
    class Propertymanagement(CreateView):
        model = Property
        success_url = reverse_lazy('')
        fields = '__all__'

#Informatión Pagina Property
def hello(request):
        return render(request, 'hello.html')

templates/property/Property_managment.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

  <div class="container mt-3">

    <h3>Nueva Gestión</h3>

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary" value="guardar">
    </form>

    <center>
     <table>
       <tbody>
         <tr>
           <th>Tipo Inmuble:</th>
           <td>{{ object.name }}</td>
         </tr>
         <tr>
           <th>Precio:</th>
           <td>{{ object.price }}</td>
         </tr>
         <tr>
           <th>Direción:</th>
           <td>{{ object.address}}</td>
         </tr>
         <tr>
           <th>Barrio:</th>
           <td>{{ object.neighborhood}}</td>
         </tr>
         <tr>
           <th>Habitaciones:</th>
           <td>{{ object.amount_rooms }}</td>
         </tr>
         <tr>
           <th>Baños:</th>
           <td>{{ object.synopsis }}</td>
         </tr>
         <tr>
           <th>Area:</th>
           <td>{{ object.length }}</td>
         </tr>
         <tr>
           <th>resumen:</th>
           <td>{{object.description}}</td>
         </tr>
       </tbody>
       </center>
     </table>


   </div>


{% endblock  %}

templates/property/property_create.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

  <div class="container mt-3">

    <h3>Nuevo Inmueble</h3>

    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="btn btn-primary" value="guardar">
    </form>

    <center>
     <table>
       <tbody>
         <tr>
           <th>Nombre inmuble:</th>
           <td>{{ object.name }}</td>
         </tr>
         <tr>
           <th>Precio:</th>
           <td>{{ object.price }}</td>
         </tr>
         <tr>
           <th>Ciudad:</th>
           <td>{{ object.city}}</td>
         </tr>
         <tr>
           <th>Barrio:</th>
           <td>{{ object.neighborhood}}</td>
         </tr>
        <tr>
           <th>Direción:</th>
           <td>{{ object.address}}</td>
         </tr>
         <tr>
            <th>Area:</th>
            <td>{{ object.length }}</td>
          </tr>
         <tr>
           <th>Años de antiguedad:</th>
           <td>{{ object.antiquity }}</td>
         </tr>
         <tr>
           <th>Cantidad de pisos:</th>
           <td>{{ object.floors }}</td>
         </tr>
         <tr>
           <th>Habitaciones:</th>
           <td>{{ object.amount_rooms }}</td>
         </tr>
         <tr>
           <th>Baños:</th>
           <td>{{ object.synopsis }}</td>
         </tr>
         <tr>
           <th>Foto:</th>
           <td>{{object.description}}</td>
         </tr>
         <tr>
           <th>Tipo inmuble:</th>
           <td>{{object.description}}</td>
         </tr>
         <tr>
           <th>Estado del inmuble:</th>
           <td>{{object.description}}</td>
         </tr>
         <tr>
           <th>Resumen:</th>
           <td>{{object.description}}</td>
         </tr>
         <tr>
           <th>Llamar a:</th>
           <td>{{object.description}}</td>
         </tr>
       </tbody>
       </center>
     </table>


   </div>


{% endblock  %}

templates/property/property_detail.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

  <div class="container mt-3">

    <center><h3><b>{{ object.name }}</b></h3></center>

    <div class="row mt-2">
      <div class="col-12">
        <center><p><img src="{% static 'Image/house1.1.jpg' %}" class="img-fluid"width="55%"></p></center>

       <center>
        <table>
          <tbody>
            <tr>
              <th>Tipo Inmuble:</th>
              <td>{{ object.name }}</td>
            </tr>
            <tr>
              <th>Precio:</th>
              <td>{{ object.price }}</td>
            </tr>
            <tr>
              <th>Direción:</th>
              <td>{{ object.address}}</td>
            </tr>
            <tr>
              <th>Barrio:</th>
              <td>{{ object.neighborhood}}</td>
            </tr>
            <tr>
              <th>Habitaciones:</th>
              <td>{{ object.amount_rooms }}</td>
            </tr>
            <tr>
              <th>Baños:</th>
              <td>{{ object.synopsis }}</td>
            </tr>
            <tr>
              <th>Area:</th>
              <td>{{ object.length }}</td>
            </tr>
            <tr>
              <th>resumen:</th>
              <td>{{object.description}}</td>
            </tr>
          </tbody>
          </center>
        </table>

    <div class="col-8">
        <p><img src="{% static 'Image/house1.jpg' %}" class="rounded float-left" alt="Responsive image" width="200"></p>
        <p><img src="{% static 'Image/house1.2.jpg' %}"class="rounded float-right" alt="Responsive image"   width="200" ></p>
        <p><center><img src="{% static 'Image/house1.3.jpg' %}" class="rounded" alt="Responsive image"  width="200"></center></p>
        </div>

      </div>
      </div>

      </div>


{% endblock  %}

templates/property/property_list.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}

  <div class="container mt-3">

    <div class="card-columns">

      {% for property in object_list %}
        <div class="card">

          <div class="hovereffect">
              <img class="card-img-top" src="../../media/{{ property.urlimage }}">
              <div class="overlay">
                 <h2>{{ property.name }}</h2>
                   <a class="info" href="{% url 'property:detail' property.id %}">Ver Más</a>
              </div>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ property.name }}</h5>
            <p class="card-text"></p>
            <p class="card-text text-center">
              <small class="text-muted ">{{ property.price }} $ | {{ property.address }} | {{ property.neighborhood}}</small>
            </p>
            <a href="#" class="btn btn-primary btn-block">Ver Inmueble</a>
          </div>
        </div>
      {% endfor %}

    </div>

  </div>

{% endblock  %}

templates/property/property_search.html
{% extends 'base/base.html' %}

{% load static %}

{% block content %}
  <div class="container mt-3">

    {% if object_list.count == 0 %}
      <div class="alert alert-secondary mt-2" role="alert">
        No hay resultados para la búsqueda: <b>"{{ search }}"</b>
      </div>
    {% else %}
      <div class="alert alert-primary mt-2" role="alert">
        Mostrando {{ object_list.count }} resultados, para la búsqueda: <b>"{{ search }}"</b>
      </div>

      <div class="card-columns">
        {% for property in object_list %}
          <div class="card">

            <div class="hovereffect">
                <img class="card-img-top" src="../../media/{{ property.urlimage }}">
                <div class="overlay">
                   <h2>{{ property.name }}</h2>
                   <a class="info" href="{% url 'property:detail' property.id %}">Ver Más</a>
                </div>
            </div>
            <div class="card-body">
              <h5 class="card-title">{{ property.name }}</h5>
              <p class="card-text"></p>
              <p class="card-text text-center">
                <small class="text-muted ">{{ property.name }} min | {{ property.name }}</small>
              </p>
              <a href="#" class="btn btn-primary btn-block">Ver Horarios</a>
            </div>
          </div>
        {% endfor %}
      </div>

    {% endif %}

  </div>
{% endblock  %}